//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cortana_Quick.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cortana_Quick.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AppBarButtonTextDelete {
            get {
                return ResourceManager.GetString("AppBarButtonTextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AppBarButtonTextSave {
            get {
                return ResourceManager.GetString("AppBarButtonTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick for Cortana.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string Auto_Delete {
            get {
                return ResourceManager.GetString("Auto_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string Database_Version {
            get {
                return ResourceManager.GetString("Database_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string First_Use {
            get {
                return ResourceManager.GetString("First_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Maximum_Date {
            get {
                return ResourceManager.GetString("Maximum_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Quick, the first audible notes extension for Cortana. Here you can use Cortana to do quick audible notes! Let&apos;s go trough a fast how-to.
        /// </summary>
        public static string Tutorial1 {
            get {
                return ResourceManager.GetString("Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        public static string Tutorial1_Header {
            get {
                return ResourceManager.GetString("Tutorial1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cortana by pressing the search button, or touching her live tile or, if your Windows Phone is updated with the Lumia Denim update, just say &apos;Hey Cortana&apos;..
        /// </summary>
        public static string Tutorial2 {
            get {
                return ResourceManager.GetString("Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, say to her Quick + I + something you want to be remembered later:&quot;.
        /// </summary>
        public static string Tutorial2_1 {
            get {
                return ResourceManager.GetString("Tutorial2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Note Parked my car at sesame street.
        /// </summary>
        public static string Tutorial2_2 {
            get {
                return ResourceManager.GetString("Tutorial2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Note left my keys on my room.
        /// </summary>
        public static string Tutorial2_3 {
            get {
                return ResourceManager.GetString("Tutorial2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Note put my torch on the dining table.
        /// </summary>
        public static string Tutorial2_4 {
            get {
                return ResourceManager.GetString("Tutorial2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Note kept my .net book in the my bag.
        /// </summary>
        public static string Tutorial2_5 {
            get {
                return ResourceManager.GetString("Tutorial2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taking a note.
        /// </summary>
        public static string Tutorial2_Header {
            get {
                return ResourceManager.GetString("Tutorial2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later, when you want to know something that you noted, open Cortana one more time and say to her:&quot;.
        /// </summary>
        public static string Tutorial3 {
            get {
                return ResourceManager.GetString("Tutorial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick where is my car?.
        /// </summary>
        public static string Tutorial3_1 {
            get {
                return ResourceManager.GetString("Tutorial3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, she will answear you with:.
        /// </summary>
        public static string Tutorial3_2 {
            get {
                return ResourceManager.GetString("Tutorial3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your car is at sesame street.
        /// </summary>
        public static string Tutorial3_3 {
            get {
                return ResourceManager.GetString("Tutorial3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you are good to go! If you have any suggestions to improve this app, review it, i&apos;ll be glad to hear your opinion. Thanks!.
        /// </summary>
        public static string Tutorial3_4 {
            get {
                return ResourceManager.GetString("Tutorial3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick where did i left my keys?.
        /// </summary>
        public static string Tutorial3_5 {
            get {
                return ResourceManager.GetString("Tutorial3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick where did i put my torch?.
        /// </summary>
        public static string Tutorial3_6 {
            get {
                return ResourceManager.GetString("Tutorial3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You left  your keys at your room.
        /// </summary>
        public static string Tutorial3_7 {
            get {
                return ResourceManager.GetString("Tutorial3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your torch is on the dinning table.
        /// </summary>
        public static string Tutorial3_8 {
            get {
                return ResourceManager.GetString("Tutorial3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asking for a note.
        /// </summary>
        public static string Tutorial3_Header {
            get {
                return ResourceManager.GetString("Tutorial3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t know where Cortana is and your country native language is English, follow this guide to enable Cortana on your Windows Phone, If you live in Germany, Spain and others, wait a little bit, this app will support your language soon..
        /// </summary>
        public static string Tutorial4 {
            get {
                return ResourceManager.GetString("Tutorial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do i enable Cortana?.
        /// </summary>
        public static string Tutorial4_Button {
            get {
                return ResourceManager.GetString("Tutorial4_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where is she?.
        /// </summary>
        public static string Tutorial4_Header {
            get {
                return ResourceManager.GetString("Tutorial4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string Verify_Input {
            get {
                return ResourceManager.GetString("Verify_Input", resourceCulture);
            }
        }
    }
}
